Repository iocage/iocage, pull requests merged in 2019-03, with the labels that each got.

#882 tkt-77574: Add assign_localhost prop
  iocage_lib/ioc_common.py
  iocage_lib/ioc_create.py
  iocage_lib/ioc_json.py
  iocage_lib/ioc_start.py
  iocage_lib/iocage.py
Labels: needs docs

#884 tkt-77574: Add property localhost_ip
  iocage_lib/ioc_common.py
  iocage_lib/ioc_create.py
  iocage_lib/ioc_json.py
  iocage_lib/ioc_start.py
Labels: needs docs

#888 tkt-76864: Split on tabs for fstab
  iocage_cli/fstab.py
  iocage_lib/ioc_fstab.py
  iocage_lib/iocage.py
Labels: backport-11.2

#895 tkt-81498: Safety check for mountpoint prop
  iocage_lib/ioc_list.py
Labels: backport-11.2, backport-11.3
