Repository iocage/iocage, pull requests merged in 2019-04, with the labels that each got.

#897 tkt-80697: Add NAT support to iocage
  iocage_lib/ioc_common.py
  iocage_lib/ioc_create.py
  iocage_lib/ioc_destroy.py
  iocage_lib/ioc_json.py
  iocage_lib/ioc_plugin.py
  iocage_lib/ioc_start.py
  iocage_lib/ioc_stop.py
  iocage_lib/iocage.py
  tests/conftest.py
  tests/data_classes.py
  tests/functional_tests/0003_create_test.py
  tests/functional_tests/0016_restart_test.py
Labels: needs docs

#917 NAS-101270 / 11.3 / Replace old fstab locations
  .gitignore
  iocage_lib/ioc_fstab.py
  iocage_lib/ioc_start.py
Labels: backport-11.2, skip jira status

#921 NAS-101365 / 11.3 / Proxy support for iocage
  iocage_cli/create.py
  iocage_cli/fetch.py
  iocage_lib/ioc_create.py
  iocage_lib/ioc_plugin.py
Labels: backport-11.2
