Repository iocage/iocage, pull requests merged in 2020-08, with the labels that each got.

#1198 NAS-106965 / 12.1 / Make sure we don't mark a succcessful package installation as failed
  iocage_lib/ioc_create.py
Labels: backport-11.3, backport-12.0, backport-12.1

#1195 NAS-107112 / 12.1 / Strip newline from plugin-properties
  iocage_lib/ioc_json.py
Labels: backport-12.0, backport-12.1, jira

#1199 NAS-106984 / 12.1 / Donot set hostname in rc.conf
  iocage_lib/ioc_create.py
Labels: backport-11.3, backport-12.0, backport-12.1

#1201 NAS-107164 / 12.1 / Default to only retrieving datasets
  iocage_lib/zfs.py
Labels: backport-12.0, backport-12.1

#1204 NAS-107235 / 12.1 / Error out update in case of malformed freebsd-update.conf
  iocage_lib/ioc_fetch.py
Labels: backport-12.0, backport-12.1

#1205 NAS-107346 / 12.1 / Improve iocage library speed by efficiently handling cache
  iocage_lib/cache.py
  iocage_lib/dataset.py
  iocage_lib/ioc_check.py
  iocage_lib/ioc_common.py
  iocage_lib/ioc_json.py
  iocage_lib/ioc_list.py
  iocage_lib/ioc_plugin.py
  iocage_lib/iocage.py
  iocage_lib/release.py
  iocage_lib/resource.py
  iocage_lib/zfs.py
Labels: backport-12.0
