Repository iocage/iocage, pull requests merged in 2020-01, with the labels that each got.

#1106 NAS-104777 / 12.0 / Change devfs ruleset handling so that configured rulesets != 4 are
  iocage_lib/ioc_common.py
  iocage_lib/ioc_json.py
  iocage_lib/ioc_start.py
Labels: backport-11.3, jira

#1131 NAS-104875 / 12.0 / Only update release property on update of jails
  iocage_lib/ioc_fetch.py
Labels: backport-12, jira

#1132 NAS-104894 / 12.0 / Use plugin manfiest names for determining plugin name
  iocage_lib/ioc_json.py
Labels: backport-12, jira

#1129 NAS-104846 / 12.0 / Listing plugin fixes
  iocage_lib/ioc_fetch.py
  iocage_lib/ioc_list.py
  iocage_lib/ioc_plugin.py
Labels: backport-12
