Repository iocage/iocage, pull requests merged in 2020-05, with the labels that each got.

#1095 NAS-106037 / 12.0 / Make MTU of VNet interfaces configurable
  .cirrus.yml
  iocage_lib/ioc_json.py
  iocage_lib/ioc_start.py
  tests/conftest.py
  tests/unit_tests/1000_lib_start_test.py
Labels: backport-12.0, jira

#1171 NAS-106031 / 12.0 / Bug fixes for proper handling of custom devfs ruleset generation in plugins
  doc/source/plugins.rst
  iocage_lib/ioc_common.py
  iocage_lib/ioc_plugin.py
  iocage_lib/ioc_start.py
Labels: backport-11.3, backport-12.0

#1174 NAS-106122 / 12.0 / Show correct admin portal in post plugin installation for NAT based plugins
  iocage_lib/ioc_common.py
  iocage_lib/ioc_list.py
  iocage_lib/ioc_plugin.py
  iocage_lib/ioc_start.py
  iocage_lib/ioc_upgrade.py
Labels: backport-12.0

#1175 NAS-106134 / 12.0 / Allow using 0 devfs ruleset
  iocage_lib/ioc_common.py
  iocage_lib/ioc_json.py
  iocage_lib/ioc_start.py
Labels: backport-12.0
